coverage:
  round: down
  precision: 2
  range: "40...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0.1%
        # advanced settings
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
    patch:
      default:
        # basic
        target: auto
        threshold: 0.1%
        # advanced settings
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
