#!/usr/bin/env bash

# Retrieving instance metadata information from within the EC2 instance
# https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html

instance_id=$(curl -s "http://169.254.169.254/latest/meta-data/instance-id")
secret=$(cat "/root/secret.txt")
password=$(echo -n "${instance_id}${secret}" | sha256sum | awk '{print $1}')
echo "rstudio-user:$password" | /usr/sbin/chpasswd
echo "Set rstudio-user password"

public_key=$(curl http://localhost:8787/auth-public-key)
instance_region=$(curl -s "http://169.254.169.254/latest/meta-data/placement/region")
aws ssm put-parameter --name "/rstudio/publickey/sc-environments/ec2-instance/${instance_id}" --value $public_key --region $instance_region --type SecureString --overwrite 
echo "Stored rstudio public key in SSM"