#!/usr/bin/env bash

instance_id=$(curl -s "http://169.254.169.254/1.0/meta-data/instance-id")
secret=$(cat "/root/secret.txt")
password=$(echo -n "${instance_id}${secret}" | sha256sum | awk '{print $1}')
echo "galileo:$password" | /usr/sbin/chpasswd
echo "Set galileo password"
