Resources:


# =============================================================================================
# Outputs
# =============================================================================================
Outputs:
  PostDeploymentRoleArn:
    Value: !GetAtt RolePostDeploymentLambda.Arn
