# 12 digit AWS Account ID for the main AWS account where the solution is (or will be) deployed
# By default, assume the master account is the same as the main (i.e. solution) account
mainAccountId: ${AWS::AccountId}

# An external id to be used in the AWS IAM role being created in the master account.
# This id will be required by the solution to assume the role in master account.
# The external id specified here MUST match the value you specify in the "Create AWS Account" screen
# when creating a member account via the RaaS solution UI
externalId: galileo
