AWSTemplateFormatVersion: 2010-09-09

Description: Service-Workbench-on-AWS ALB for RStudio IDE

Parameters:
  Namespace:
    Type: String
    Description: An environment name that will be prefixed to resource names
  VPC:
    Description: The VPC in which the ALB will reside
    Type: AWS::EC2::VPC::Id
  Subnet1:
    Description: The VPC Subnet1 in which the ALB will reside
    Type: AWS::EC2::Subnet::Id
  Subnet2:
    Description: The VPC Subnet2 in which the ALB will reside
    Type: AWS::EC2::Subnet::Id
  ACMSSLCertARN:
    Type: String
    Description: The ARN of the AWS Certificate Manager SSL Certificate to associate with the Load Balancer
  IsAppStreamEnabled:
    Type: String
    AllowedValues: [true, false]
    Description: Is AppStream enabled for this workspace

Conditions:
  AppStreamEnabled: !Equals [!Ref IsAppStreamEnabled, 'true']
  AppStreamDisabled: !Equals [!Ref IsAppStreamEnabled, 'false']

Resources:
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: 'text/plain'
            MessageBody: 'Forbidden'
            StatusCode: '403'
      LoadBalancerArn:
        Ref: ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-2016-08
      Certificates:
        - CertificateArn: !Ref ACMSSLCertARN
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref Namespace
      Scheme:
        - !If
          - AppStreamEnabled
          - 'internal'
          - 'internet-facing'
      Subnets:
        - Ref: Subnet1
        - Ref: Subnet2
      SecurityGroups:
        - Ref: ALBSecurityGroup
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - !If
          - AppStreamEnabled
          - !Ref 'AWS::NoValue'
          - CidrIp: '0.0.0.0/0'
            FromPort: 443
            ToPort: 443
            IpProtocol: tcp
      GroupDescription: ALB SecurityGroup
      VpcId: !Ref VPC
Outputs:
  LoadBalancerArn:
    Description: ARN of Application Load Balancer
    Value: !Ref ApplicationLoadBalancer
  ALBDNSName:
    Description: DNS Name of Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
  ListenerArn:
    Description: ARN of Application Load Balancer Listener
    Value: !Ref ALBListener
  ALBSecurityGroupId:
    Description: Security Group of Application Load Balancer Listener
    Value: !Ref ALBSecurityGroup
