# For testing purposes only
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.192.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PrivateAppStreamSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: 10.192.20.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Private AppStream Subnet

  PrivateWorkspaceSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: 10.192.21.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Private Workspace Subnet

  PrivateWorkspaceRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC

  WorkspaceSubnetAssociationRouteTable:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PrivateWorkspaceSubnet
      RouteTableId: !Ref PrivateWorkspaceRouteTable

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html
  S3Endpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:ListAllMyBuckets'
            Resource:
              - '*'
      RouteTableIds:
        - !Ref PrivateWorkspaceRouteTable
      VpcEndpointType: Gateway
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref VPC

  KMSEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      SubnetIds:
        - !Ref PrivateWorkspaceSubnet
      PrivateDnsEnabled: true
      VpcEndpointType: Interface
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.kms'
      VpcId: !Ref VPC

  STSEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      SubnetIds:
        - !Ref PrivateWorkspaceSubnet
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.sts'
      VpcId: !Ref VPC

  EC2Endpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      SubnetIds:
        - !Ref PrivateWorkspaceSubnet
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ec2'
      VpcId: !Ref VPC

  # Allows creating of presigned URL
#  SagemakerApiEndpoint:
#    Type: 'AWS::EC2::VPCEndpoint'
#    Properties:
#      SubnetIds:
#        - !Ref PrivateAppStreamSubnet
#      VpcEndpointType: Interface
#      PrivateDnsEnabled: true
#      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.sagemaker.api'
#      VpcId: !Ref VPC
#
#  SagemakerRuntimeEndpoint:
#    Type: 'AWS::EC2::VPCEndpoint'
#    Properties:
#      SubnetIds:
#        - !Ref PrivateAppStreamSubnet
#      VpcEndpointType: Interface
#      PrivateDnsEnabled: true
#      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.sagemaker.runtime'
#      VpcId: !Ref VPC

  # https://docs.aws.amazon.com/sagemaker/latest/dg/notebook-interface-endpoint.html
  SagemakerNotebookEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      SubnetIds:
        - !Ref PrivateAppStreamSubnet
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      ServiceName: !Sub 'aws.sagemaker.${AWS::Region}.notebook'
      VpcId: !Ref VPC
