name: CodePipeline Test
on:
  push:
    branches:
      - cicd-notification
jobs:
  check-gh-status:
    name: Check Github Status
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Wait until CodePipeline status is shown
        run: |
          npm install
          node checkCommitStatus.js ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.sha }}
#          waitTimePerLoopInSeconds=30
#          totalWaitTimeInSeconds=3600
#          iteration=0
#          status=""
#          while [[ $((iteration * waitTimePerLoopInSeconds)) -le "$totalWaitTimeInSeconds" &&  "$status" != "success" && "$status" != "error" ]]; do
#              echo "$iteration" iterations
#              iteration=$(($iteration + 1))
#              sleep "$waitTimePerLoopInSeconds"
#              response=$(curl --request GET \
#          --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/statuses \
#          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
#          --header 'content-type: application/json')
#              echo $response
#              status=$(node parseGHStatus.js "$response")
#              echo "$status"
#          done
#          if [[ $status == "success" ]]; then
#              exit 0
#          else
#              exit 1
#          fi
        working-directory: scripts/check-commit-status

  merge-develop-to-mainline:
    name: Merge develop to mainline
    runs-on: ubuntu-18.04
    needs: [ check-gh-status ]
    steps:
      - name: Merge to mainline
        run: |
          echo "Merging to mainline"
