#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Deploy & Integration Test
on:
  push:
    branches:
      - develop
jobs:
  pre-deployment-check:
    name: Pre deployment check
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: "Block Concurrent Deployments"
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy to Dev
    runs-on: ubuntu-18.04
    needs: pre-deployment-check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: ./scripts/install.sh
      - name: Build all packages
        run: ./scripts/build-all-packages.sh
      - name: Deploy
        env:
          STAGE_NAME: e2etest
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cp ./main/end-to-end-tests/e2eGitHubConfig.yml ./main/config/settings/${STAGE_NAME}.yml
          ./scripts/environment-deploy.sh ${STAGE_NAME}
  integration-test:
    name: Integration test
    runs-on: ubuntu-18.04
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install pnpm and system libraries
        run: |
          npm install -g pnpm
          sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install dependencies
        run: pnpm install
        working-directory: main/integration-tests
      - name: Run integration tests
        run: ./scripts/run-integration-tests.sh ${STAGE_NAME}
        working-directory: ./
        env:
          DEPLOYMENT_BUCKET: ${{ secrets.DEPLOYMENT_BUCKET}}
          STAGE_NAME: e2etest
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
  cypress-test:
    name: Cypress test
    runs-on: ubuntu-18.04
    needs: integration-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install pnpm and system libraries
        run: |
          npm install -g pnpm
          sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install dependencies
        run: pnpm install
        working-directory: main/end-to-end-tests
      - name: Run cypress test
        run: pnpm run cypress:run-tests:github
        working-directory: main/end-to-end-tests
        env:
          # Env parameters for cypress tests need header 'CYPRESS_' or 'cypress_'
          # Cypress will strip the header and pass it to the tests
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL}}
          CYPRESS_researcherEmail: ${{ secrets.CYPRESS_RESEARCHER_EMAIL}}
          CYPRESS_researcherPassword: ${{ secrets.CYPRESS_RESEARCHER_PASSWORD}}
  merge-develop-to-mainline:
    name: Merge develop to mainline
    runs-on: ubuntu-18.04
    needs: cypress-test
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.MERGE_TOKEN}}
          fetch-depth: 0
      # There's no way for github actions to push to a protected branch. This is a workaround
      # See https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/30
      - name: Temporarily disable branch protection
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
          owner: awslabs
          repo: service-workbench-on-aws
          branch: mainline
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
      - name: Merge to mainline
        run: |
          git checkout mainline
          echo
          echo "  Attempting to merge the 'develop' branch ($(git log -1 --pretty=%H develop))"
          echo "  into the 'mainline' branch ($(git log -1 --pretty=%H mainline))"
          echo
          git merge --ff-only --no-edit develop
          git push origin mainline
      - name: Enable branch protection
        uses: octokit/request-action@v2.x
        if: always() # Make sure to enable branch protection even if other steps fail
        with:
          route: POST /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
          owner: awslabs
          repo: service-workbench-on-aws
          branch: mainline
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}
