#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Unit Tests & Code Analysis
on:
  pull_request:
    branches:
      - develop
      - "feat-*"
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  schedule:
    - cron: '0 0 * * *'
jobs:
  CodeQL-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1